### PR TITLE
fix: op e2e test

### PR DESCRIPTION
**Pull request by lesterli**
## Summary

This PR fixes the op e2e tests:
* only start one consumer FP
   * change the `TestOpMultipleFinalityProviders`  to `TestFinalityProviderLifeCycle`
* check if FP exists before start FP to fix the FP already exists

## Test Plan

```
make lint
make test
make test-e2e-op
```

### CODE REVIEW

**Review by SebastianElvis — APPROVED** [review]
Code wise lgtm. CI seems to be failed though

**Comment by lesterli** [comment]
> CI seems to be failed though

Yes, it is weird that all unit tests were passed at my laptop.

**Comment by bap2pecs** [comment]
> no op e2e in CI, can we enable it?

I checked the logs and it says "file /home/runner/work/finality-provider/finality-provider/itest/opstackl2/devnet-data/allocs-l1.json does not exist"

image

**Comment by bap2pecs** [comment]
> I checked the logs and it says "file /home/runner/work/finality-provider/finality-provider/itest/opstackl2/devnet-data/allocs-l1.json does not exist"

cc @lesterli jfyi

**Pull request merged**
